# Generated by Django 5.2.6 on 2025-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("on_message", "On Message"),
                            ("on_confirmation", "On Confirmation"),
                        ],
                        default="on_message",
                        max_length=20,
                    ),
                ),
                ("condition", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[("escalate", "Escalate"), ("reject", "Reject")],
                        default="reject",
                        max_length=20,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("is_enabled", models.BooleanField(default=True)),
                ("response", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
